name: Build and release WebAssembly image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-file-system-image:
    uses: r-wasm/actions/.github/workflows/release-file-system-image.yml@v2
    permissions:
      # For publishing artifact files to the release
      contents: write
      # To download GitHub Packages within action
      repository-projects: read
